# Ex - GroupBy

### Introduction:

GroupBy can be summarized as Split-Apply-Combine.

Special thanks to: https://github.com/justmarkham for sharing the dataset and materials.

Check out this [Diagram](http://i.imgur.com/yjNkiwL.png)  
### Step 1. Import the necessary libraries

In [1]:
import pandas as pd

### Step 2. Import the dataset from this [address](https://raw.githubusercontent.com/justmarkham/DAT8/master/data/drinks.csv).

### Step 3. Assign it to a variable called drinks.

In [3]:
drinks = pd.read_csv('https://raw.githubusercontent.com/justmarkham/DAT8/master/data/drinks.csv')

### Step 4. Which continent drinks more beer on average?

In [7]:
drinks.groupby('country')['beer_servings'].mean().reset_index().sort_values('beer_servings', ascending=False)

            country  beer_servings
118         Namibia          376.0
45   Czech Republic          361.0
61            Gabon          347.0
64          Germany          346.0
97        Lithuania          343.0
..              ...            ...
112          Monaco            0.0
155         Somalia            0.0
146    Saudi Arabia            0.0
130        Pakistan            0.0
144      San Marino            0.0

[193 rows x 2 columns]

### Step 5. For each continent print the statistics for wine consumption.

In [9]:
drinks.groupby('continent')['wine_servings'].describe()

           count        mean        std  min   25%    50%     75%    max
continent
AF          53.0   16.264151  38.846419  0.0   1.0    2.0   13.00  233.0
AS          44.0    9.068182  21.667034  0.0   0.0    1.0    8.00  123.0
EU          45.0  142.222222  97.421738  0.0  59.0  128.0  195.00  370.0
OC          16.0   35.625000  64.555790  0.0   1.0    8.5   23.25  212.0
SA          12.0   62.416667  88.620189  1.0   3.0   12.0   98.50  221.0

### Step 6. Print the mean alcohol consumption per continent for every column

In [16]:
drinks.groupby(['continent', 'country']).mean()

                        beer_servings  spirit_servings  wine_servings  \
continent country
AF        Algeria                25.0              0.0           14.0
          Angola                217.0             57.0           45.0
          Benin                  34.0              4.0           13.0
          Botswana              173.0             35.0           35.0
          Burkina Faso           25.0              7.0            7.0
...                               ...              ...            ...
SA        Paraguay              213.0            117.0           74.0
          Peru                  163.0            160.0           21.0
          Suriname              128.0            178.0            7.0
          Uruguay               115.0             35.0          220.0
          Venezuela             333.0            100.0            3.0

                        total_litres_of_pure_alcohol
continent country
AF        Algeria                                0.7
          Angola                                 5.9
          Benin                                  1.1
          Botswana                               5.4
          Burkina Faso                           4.3
...                                              ...
SA        Paraguay                               7.3
          Peru                                   6.1
          Suriname                               5.6
          Uruguay                                6.6
          Venezuela                              7.7

[170 rows x 4 columns]

### Step 7. Print the median alcohol consumption per continent for every column

In [17]:
drinks.groupby(['continent', 'country']).median()

                        beer_servings  spirit_servings  wine_servings  \
continent country
AF        Algeria                25.0              0.0           14.0
          Angola                217.0             57.0           45.0
          Benin                  34.0              4.0           13.0
          Botswana              173.0             35.0           35.0
          Burkina Faso           25.0              7.0            7.0
...                               ...              ...            ...
SA        Paraguay              213.0            117.0           74.0
          Peru                  163.0            160.0           21.0
          Suriname              128.0            178.0            7.0
          Uruguay               115.0             35.0          220.0
          Venezuela             333.0            100.0            3.0

                        total_litres_of_pure_alcohol
continent country
AF        Algeria                                0.7
          Angola                                 5.9
          Benin                                  1.1
          Botswana                               5.4
          Burkina Faso                           4.3
...                                              ...
SA        Paraguay                               7.3
          Peru                                   6.1
          Suriname                               5.6
          Uruguay                                6.6
          Venezuela                              7.7

[170 rows x 4 columns]

### Step 8. Print the mean, min and max values for spirit consumption.
#### This time output a DataFrame

In [18]:
drinks['spirit_servings'].agg(['mean', 'min', 'max'])

mean     80.994819
min       0.000000
max     438.000000
Name: spirit_servings, dtype: float64